#!/bin/bash
export LANG=en_US.UTF-8

input=$(pbpaste)
result=$(/Users/yay/workspace/genspark-agent/tools/omega-runner-noconfirm.sh "$input" 2>&1)
echo "$result" | pbcopy

osascript -e 'tell application "System Events" to keystroke "v" using command down'
sleep 0.3
osascript -e 'tell application "System Events" to keystroke return'
osascript -e 'display notification "Done!" with title "Omega"'
